title: EAP
lang: en
description: a catchy description for your project
markdown: kramdown

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  enable: true
  remove_originals: false
  with_frontmatter: false

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
