title: EAP
lang: en
description: Empirical Asset Pricing
markdown: kramdown

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
